### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by SeekPoint** [adrinjalali/Network-Classifier#4]

**Comment by adrinjalali** [comment]
This was the research I was doing, and it's a messy code, now that I look at it. I guess the last commit was 3 years ago or so.

Anyhow, the cleaner branch is the _devel_ branch, and you can see the usage [here](https://github.com/adrinjalali/Network-Classifier/blob/devel/run.py).

**Comment by SeekPoint** [comment]
so would you please upload the data used in run.py?

**Comment by adrinjalali** [comment]
I can't for two reasons:
 - the data is large
 - the data is provided by TCGA, which you can get yourself. But also, you'll need to agree with their terms and conditions to get the data. Therefore it can't be share here.

**Comment by SeekPoint** [comment]
where is the link? thanks
